---
- name: Clone Git repo and run Python code in a virtualenv
  hosts: localhost
  vars:
    git_repo_url: 'https://github.com/shendeumesh57/python.git'  # Replace this
    repo_dest: '/tmp/my_repo'
    venv_path: '/tmp/my_repo/venv'

  tasks:


    - name: Clone Git repository
      git:
        repo: "{{ git_repo_url }}"
        dest: "{{ repo_dest }}"
        force: yes

    - name: Create Python virtual environment
      command: python3 -m venv {{ venv_path }}
      args:
        creates: "{{ venv_path }}/bin/activate"

    - name: Install dependencies from requirements.txt (if present)
      shell: |
        source {{ venv_path }}/bin/activate
        pip install -r requirements.txt
      args:
        chdir: "{{ repo_dest }}"
      when: "'requirements.txt' in lookup('ansible.builtin.fileglob', repo_dest + '/*')"

    - name: Run Python script inside virtual environment
      shell: |
        source {{ venv_path }}/bin/activate
        python hello.py
      args:
        chdir: "{{ repo_dest }}"
